### ISSUE TITLE
Improvement for v0.0.2

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/profile_chrome_extension#7]
# Task 1 : Add more options for profiles:

- [X] Portfolio
- [X] LinkedIn
- [X] GitHub
- [X] Twitter
- [X] Medium
- [X] Facebook
- [X] Instagram
- [X] Kaggle 
- [X] Gmail
- [X] Custom Mail (Default mail)
- [x] Leetcode

# Assets
- [x] Design custom icons
- [x] Custom Design Favicon(s) (Default: SG . Any design works too! __Do not use online images__)

# CSS
- [x] Separate the CSS
- [x] Try to put some transitions/effects
- [x] Divide the page(extension) into two sets of 4 profiles

# Font

- [x] Improve the font
- [ ] Use an appropriate text animation

# Click and Edit

- [ ] Have an edit button
- [ ] Use Javascript(popup.js) to enable updating,deleting,adding profile options

# Update the documentation

**Comment by Adyasha8105** [comment]
I am working on
1. Add more options for profiles.
2.  Improve the font
3. Try to put some transitions/effects
4.  Design custom icons
5.  Divide the page(extension) into two sets of 5 profiles

and I have completed this task  ( Custom Design Favicon ).

**Comment by Adyasha8105** [comment]
I am working on

1. favicon
2. Leetcode
3. Improve the font
4. Design custom icons
